### ISSUE TITLE
貌似点击说说正文会导致crash

### ISSUE THREAD

**Issue by Joneze** [TigerWf/WFCoretext#3]
点击说说正文会导致crash，**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 2]'  想修改，但是无从下手，光看懂你这份demo已经花了半天时间了。先膜拜一下··

**Comment by TigerWf** [comment]
嗯嗯  之前写的好乱 后来加的 没注意到。。。多谢提醒

**Comment by Joneze** [comment]
^ - ^ 如果有空修复一下 就完美了。

**Comment by Joneze** [comment]
OK, close issue

**Comment by Joneze** [comment]
刚刚重新看了下代码，发现在这个方法里 加上这句 能暂时修复这个bug ，缺点就是还是会有点击阴影效果。

#pragma mark - 点评论整块区域的回调
- (void)clickRichText:(NSInteger)index replyIndex:(NSInteger)replyIndex{
  
  if (replyIndex == -1) {
      return;
  }

**Comment by TigerWf** [comment]
那个阴影是故意加上去的  还有 最新版本貌似已经修复了bug了吧 难道还有？？

**Comment by Joneze** [comment]
原来你已经修复了啊，哈哈 ，我没注意看呢！！
